#pragma config(Sensor, S3,     lightSensor,         sensorLightActive)
#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(NXT)

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                           - Line Tracker -                                             *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program allows your taskbot to follow a line in reverse.                                         *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Light Sensor is attached to the back of the robot.                                          *|
|*    2)  Be sure to take readings of your Light Sensor over the light and dark areas.  Once you have     *|
|*        the values, add them and divide by 2 to find your threshold.  Then, use your threshold as a     *|
|*        comparison in your program.                                                                     *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port B                  motorB              NXT                 Right motor                         *|
|*    Port C                  motorC              NXT                 Left motor                          *|
|*    Port 1                  lightSensor         Light Sensor        Back mounted                        *|
\*---------------------------------------------------------------------------------------------------4246-*/
void checkBTLinkConnected(){
	if (nBTCurrentStreamIndex >= 0)
	  return; // An existing Bluetooth connection is present.
}

task Send(){
	ubyte sensor[2];
	//char msg[] ="ola";
	//ubyte sensor1[1];

	checkBTLinkConnected();
	setBluetoothRawDataMode();
	while (!bBTRawMode){
		// Wait for Bluecore to enter raw data mode
		wait1Msec(50);
	}
	while (true){
		sensor[0] = SensorValue(lightSensor);
		sensor[1] = SensorValue(touchSensor);
		nxtWriteRawBluetooth(sensor, 2);
		wait1Msec(2);
		//sendMessage(msg);
	}
	return;
}

task main(){
   StartTask(Send);
   wait1Msec(50);                        // The program waits 50 milliseconds to initialize the light sensor.

  // while(true)                           // Infinite loop
  // {
  //    if(SensorValue[lightSensor] < 45)  // If the Light Sensor reads a value less than 45:
  //    {
  //      motor[motorB] = 60;                  // Motor B is run at a 60 power level.
	//	motor[motorC] = 20;                  // Motor C is run at a 20 power level.
  //    }
  //    else                               // If the Light Sensor reads a value greater than or equal to 45:
  //    {
  //      motor[motorB] = 20;                  // Motor B is run at a 20 power level.
	//	motor[motorC] = 60;                  // Motor C is run at a 60 power level.
  //    }
  // }
}
